version: '3.1'

services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    network_mode: "host"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    network_mode: "host"