version: '3.1'

services:

  mysql:
    image: mysql:5.7
    volumes:
      - todo-mysql-data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: myDb




volumes:
  todo-mysql-data:























































